<?php
$title = 'Add new album';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>

<?php
$album = $form->get('title');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Album title');

$artist = $form->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Artist');

$date = $form->get('date');
$date->setAttribute('class', 'form-control');

$age = $form->get('age');
$age->setAttribute('class', 'form-control');
$age->setAttribute('placeholder', '0');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('album', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($album) ?>
    <?= $this->formElement($album) ?>
    <?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($artist) ?>
    <?= $this->formElement($artist) ?>
    <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($date) ?>
    <?= $this->formElement($date) ?>
    <?= $this->formElementErrors()->render($date, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($age) ?>
    <?= $this->formElement($age) ?>
    <?= $this->formElementErrors()->render($age, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formHidden($form->get('id'));
echo $this->formSubmit($submit);
echo $this->form()->closeTag();
?>

<script>
    $("input[name='date']").blur(function(){
        var el = this;
        var date = $(el).val();

        if(date != "") {
            date = new Date(date);
            var today = new Date();
            var age = Math.floor((today-date) / (365.25 * 24 * 60 * 60 * 1000));
            $("input[name='age']").val(age);
        }
    });
</script>
