<?php
$title = 'Delete album';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($album->title) ?>" by
    "<?= $this->escapeHtml($album->artist) ?>"?
</p>

<?php
$form->setAttribute('action', $this->url('album', ['action' => 'delete', 'id' => $id]));
$form->prepare();

echo $this->form()->openTag($form);

$album_id = $form->get('id');
$album_id->setValue($album->id);
echo $this->formHidden($form->get('id'));

$del = $form->get('del');
$del->setAttribute('class', 'btn btn-danger');
$del->setValue('Yes');
echo $this->formSubmit($del);

$del = $form->get('del');
$del->setAttribute('class', 'btn btn-success');
$del->setValue('No');
echo $this->formSubmit($del);
echo $this->form()->closeTag();
?>