<?php

$title = 'My albums';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('album', ['action' => 'add']) ?>">Add new album</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Release Date</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($albums as $album) : ?>
        <tr>
            <td><?= $this->escapeHtml($album->title) ?></td>
            <td><?= $this->escapeHtml($album->artist) ?></td>
            <td><?= $this->escapeHtml($album->date) ?></td>
            <td>
                <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
                <button class="del" id="<?php echo $album->id; ?>">Delete</button>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<script>
    $(document).ready(function() {
        $('.del').click(function(event){
            //event.preventDefault();
            var el = this;
            var id = this.id;

            $.post('album/delete/' + id, {},
                function(data) {
                    if(data.response == true) {
                         $(el).closest('tr').fadeOut(300, function(){
                             $(this).remove();
                         });
                    }
                }, 'json');
        });
    });
</script>